### ISSUE TITLE
Compiling on macOS and use with Sapphire RX580 Nitro+

### ISSUE THREAD

**Issue by hamstero** [matszpk/amdcovc#30]
I'm trying to compile on macOS 10.14.2 (Hackintosh, i7-8700). Aiming to undervolt and adjust fan curve of Sapphire RX580 Nitro+. I have Wattman available in Windows, but need it to work in macOS also. Anyone having luck with this?

Having installed (make install-lib) this:

https://github.com/pciutils/pciutils

I get this error:

$ make
g++ -Wall -O3 -std=c++11   -c -o amdcovc.o amdcovc.cpp
g++ -Wall -O3 -std=c++11  -o amdcovc amdcovc.o -ldl -lpci -lm -pthread
Undefined symbols for architecture x86_64:
  "_IOConnectCallStructMethod", referenced from:
      _darwin_read in libpci.a(darwin.o)
      _darwin_write in libpci.a(darwin.o)
  "_IOObjectRelease", referenced from:
      _darwin_detect in libpci.a(darwin.o)
  "_IOServiceGetMatchingService", referenced from:
      _darwin_detect in libpci.a(darwin.o)
  "_IOServiceMatching", referenced from:
      _darwin_detect in libpci.a(darwin.o)
  "_IOServiceOpen", referenced from:
      _darwin_detect in libpci.a(darwin.o)
  "_kIOMasterPortDefault", referenced from:
      _darwin_detect in libpci.a(darwin.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [amdcovc] Error 1
